import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import UpperNav from "./components/navs/UpperNav";

const DM = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${DM.className} overflow-x-hidden max-w-[1800px]`}>
        <UpperNav />
        {children}
      </body>
    </html>
  );
}
